### ISSUE TITLE
#1 AWS

### ISSUE THREAD

**Issue by uuuo3o** [INU-CSE-STUDY/Doki-Doki-Ultimate-Refactoring-Missions#5]
AWS 구축이 하고 싶었다.
옛날에는 IPv4 써도 돈을 안 받아서 그냥 쉽게,, RDS 구축하고 연결해서 썼다.
지금은 옛날처럼 수동으로 안하고 CI/CD 파이프라인도 어찌저찌 구축도 했는데 갑자기 AWS가 IPv4 사용하면 돈 내라고 시켜서 어쩔 수 없이 어려운 길을 택하게 되었다.
EC2와 연결된 RDS를 만들어서, 지금 EC2 서버에 ubuntu 계정으로 접속하지 않는 한 DB 접근이 안되는 사람이 되었다.
이걸 해결하기 위해 yml파일에 ssh 연결해서 어떻게든 로컬에서 돌아가게 할 거다.
우리는 승리한다.
이 바보같은 AWS

**Comment by jang010505** [comment]
결론 아마존 나빠요...

**Comment by jang010505** [comment]
수고하셨습니다.
